---
title: "Ho Chi Minh AQI Analyis"
output: html_document
author: Priya Yadav
---
```{r, echo= False}
#loading libraries for data wrangling , binning and visualization
library(dplyr)
library(ggplot2)
library(OneR)
```

```{r}
# reading the master dataset for Ho Chi Minh City combined for all years, path D:/Semester 1/DANA/Team Project
df <- read.csv("D:/Semester 1/DANA/Team Project/HoChiMinhCity_PM2.5_2017_2021_Master_MTD.csv")
View(df)
```

```{r}
summary(df)
```


```{r}
# Check if there are any null values in the dataframe
any(is.na((df)))
```


```{r}
#year and month wise distribution
df %>% 
    group_by(Year,Month) %>% 
    summarise(Total_Count  = n())

```
```{r}
#Remove Jan month value from the dataset as there is only one value from the month of Jan from 2018,2019,2020 and 2021 which isn't significant for the analysis

df= subset(df,Month != 1)
df %>% 
    group_by(Year,Month) %>% 
    summarise(Total_Count  = n())

```


```{r}
list("Summary" = summary(df$AQI), 
     "Standard Deviation" = sd(df$AQI, na.rm=TRUE), 
     "Range" = range(df$AQI, na.rm=TRUE), 
     "Inter-Quartile Range(IQR)" = IQR(df$AQI, na.rm=TRUE)) 
```


```{r}

#Check AQI distribution in the data
df %>% 
    group_by(AQI_Category) %>% 
    summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2)) %>%arrange(desc(Total_Count))
```


```{r}
# AQI distribution for the overall data
hist(df$AQI, 
     main = "Histogram for AQI", 
     xlab = "AQI",
     freq = TRUE,
    # probability = TRUE,
     breaks = 10,
     border = "Blue",
     col = "Turquoise",
     labels = TRUE,
     las=1   ,
     ylim = c(0,1200),
     xlim = c(0,200))
```
```{r}
# YOY AQI distribution ,coord_flip()
df$Year_New = factor(df$Year, order = TRUE, labels = c("2016","2017", "2018", "2019", "2020", "2021"))
ggplot(df, aes(x = Year_New, y = AQI, fill= Year_New) )+
    geom_boxplot() +
      stat_summary(fun.y = mean,
        geom = "point",
        size = 2,
        color = "red")+
    theme_classic()
```


```{r}

# BAr plot for AQI Category

df %>% 
    group_by(AQI_Category) %>% 
    summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2))  %>%
    ggplot(aes(x = reorder(AQI_Category, -Total_Count), y = Total_Count))+ geom_col(fill="pink",color = "brown")+
    geom_text(aes(label = Total_Count), vjust = -0.2,size = 4)+
     labs(x = "AQI Category",
          y = "Total Count",
          title = "Data Distribution on AQI Category")+
   theme(axis.text.x = element_text(angle = 0),plot.title = element_text(hjust = 0.5)) 
   
```

```{r}
# Proportion distribution of AQI Category on yearly basis
df %>% 
    group_by(Year,AQI_Category) %>% 
    summarise(Total_Count  = n())  %>%
 ggplot(aes(x = Year, y = Total_Count,fill= AQI_Category))+ geom_col(color = "brown", width =0.5,position = "fill")+
  scale_fill_brewer(palette = "Dark2")+
    theme(axis.text.x = element_text(angle = 0),plot.title = element_text(hjust = 0.5)) +
  theme(legend.position="bottom")

```
```{r }
# Check AQI distribution for Pre and Post COVID period
#Year 2020 has only ~20% of the data with AQI categorized as Unhealthy which is lowest amongst all years
df %>% subset(Year %in% c(2019,2020,2021)) %>%
    group_by(Year,AQI_Category) %>% 
    summarise(Total_Count  = n())  %>%
 ggplot(aes(x = Year, y = Total_Count,fill= AQI_Category))+ geom_col(color = "brown", position = "fill")+
  scale_fill_brewer(palette = "Set3")

```


```{r Fig1, fig.height=5, fig.width=15}
# Check hourly distribution of AQI Catgeory in the data
df %>% 
    group_by(Hour,AQI_Category) %>% 
    summarise(Total_Count  = n()) %>%
  ggplot(aes(x = Hour, y = Total_Count,fill= AQI_Category))+ geom_col(color = "brown", width =0.5,position = "fill")+
  scale_fill_brewer(palette = "Dark2")

```

```{r}
#Above chart shows the peak hours where AQI Category = Unhealthy for more than 50% of the data 
# Hours = 8,9,10,11,12,13 

# Late night and early morning 75% of the data has AQI in the range of Good to Moderate (Hours = 21,22,23,0,1,2)
```

```{r}

# Merging the given data with external data gathered for weather paramters
df_weather <- read.csv("D:/Semester 1/DANA/Team Project/weather.csv")
View(df_weather)

new_df <- merge(df,df_weather,by = c("Day","Month","Year","Hour"))
View(new_df)
```

```{r}
# Checking distribution on Weather Description
new_df %>% 
    group_by(weatherDesc) %>% 
    summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2)) %>%arrange(desc(Total_Count))
```


```{r}

# Clubbing related weather description for further analysis

new_df$weatherDescNew <- ifelse(new_df$weatherDesc %in% c("Partly cloudy","Clear","Sunny","Patchy rain possible","Light rain shower","Cloudy","Moderate or heavy rain shower"),new_df$weatherDesc , "Others")

new_df %>% 
    group_by(weatherDescNew) %>% 
    summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2)) %>%arrange(desc(Total_Count))
```



```{r Fig1, fig.height=5, fig.width=15}
# Relation between AQI Category and Weather Description
new_df %>% 
    group_by(weatherDescNew,AQI_Category) %>% 
    summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2)) %>%
  ggplot(aes(reorder(x = weatherDescNew, -Total_Count), y = Total_Count,fill= AQI_Category))+ 
  geom_bar( stat="identity")+
       labs(x = "Weather Description",
          y = "Total Count",
          title = "Data Distribution on Weather Description")+
   scale_fill_brewer(palette = "Set2") + theme(legend.position="bottom")


```


```{r Fig1, fig.height=5, fig.width=15}
# AQI Category proportion distribution on Weather Description 
new_df %>% 
    group_by(weatherDescNew,AQI_Category) %>% 
    summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2)) %>%
  ggplot(aes(reorder(x = weatherDescNew, -Total_Count), y = Total_Count,fill= AQI_Category))+ 
  geom_bar( position = "fill",stat="identity",width =0.7)+
       labs(x = "Weather Description",
          y = "Proportion",
          title = "Data Distribution on Weather Description")+
   scale_fill_brewer(palette = "Set2")

## No significant relation between AQI and Weather Description

```
```{r}
# Check effect of windspeed on AQI, Histogram for WindSpeed

hist(new_df$windspeedKmph, 
     main = "Histogram for Wind Speed", 
     xlab = "Windspeed",
     freq = TRUE,
     #probability = TRUE,
     breaks = 10,
     border = "Blue",
     col = "Turquoise",
     labels = TRUE,
     las=1   ,
     ylim = c(0,1200))
```

```{r}
# Box Plot for WindSpeed
boxplot(new_df$windspeedKmph,
        las=1,
        main = "Box Plot for WindSpeed",
        #xlab = "Number of quantitues sold",
        ylab = "WindSpeed",
        col = "Turquoise",
        border = "blue",
        horizontal = F,
        outline = T)
```




```{r}

# Binning WindSpeed data points into relevant categories using content method which gives intervals of equal content via quantiles , 


new_df$windspeed_Cat <- bin( new_df$windspeedKmph, nbins = 3,method = "content",label = c("Low (0-6)","Medium (7-9)","High (10-25)"))
 

new_df %>% group_by(windspeed_Cat) %>%
   summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2))

```

```{r Fig1, fig.height= 4, fig.width=8}
# AQI CAtegory distribution over WindSpeed
new_df %>% group_by(windspeed_Cat,AQI_Category) %>%
   summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2)) %>%
  ggplot(aes(x = windspeed_Cat, y = Total_Count,fill= AQI_Category))+ 
  geom_bar(stat="identity",width =0.4, color = "Dark Green")+
       labs(x = "Wind Speed",
          y = "Total Count",
          title = "Data Distribution on Wind Speed")+
   scale_fill_brewer(palette = "PiYG", direction = -1) +theme(legend.position="bottom")
```



```{r Fig1, fig.height=4, fig.width=8}

# WindSpeed proportion distribution over AQI ACtegory
new_df %>% group_by(windspeed_Cat,AQI_Category) %>%
   summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2)) %>%
  ggplot(aes(x = windspeed_Cat, y = Total_Count,fill= AQI_Category))+ 
  geom_bar(position = "fill",stat="identity",width =0.4, color = "Dark Green")+
       labs(x = "Wind Speed",
          y = "Proportion",
          title = "Data Distribution on Wind Speed")+
   scale_fill_brewer(palette = "PiYG", direction = -1)+theme_minimal()+theme(legend.position="bottom")

```
```{r}
#Above figure shows that as the wind speed increases AQI improves. For wind speed categorized under "High", 76% of the #data has AQI as Low and Medium
```

```{r }
# Data Distribution for Visibility Variable
new_df %>% 
    group_by(visibility) %>% 
    summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2)) %>%
  ggplot(aes(x = visibility, y = Total_Count))+ 
  geom_bar( stat="identity", fill = "Orange", color = "Brown")+
   geom_text(aes(label=Total_Count), vjust=-0.3, size=3.5)+
       labs(x = "Visibility",
          y = "Total Count",
          title = "Data Distribution on Visibility") +
  theme_minimal() +theme(legend.position="bottom")

```

```{r}
# Check effect of humidity on Air Quality, Histogram for Humidity

hist(new_df$humidity, 
     main = "Histogram for Humidity", 
     xlab = "Humidity",
     freq = TRUE,
     #probability = TRUE,
     breaks = 10,
     border = "Turquoise",
     col = "Pink",
     labels = TRUE,
     las=1   ,
     ylim = c(0,800),
     xlim = c(20,100))

```

```{r}
# Binning Humidity Variable for analysis

#, labels = c("Vey Low", "Low", "Medium","High", "Very High")
 new_df$humidity_cat <- cut( new_df$humidity,  c(-Inf, 30, 60, Inf), labels = c("Dry","Normal","Humid"))
 

new_df %>% group_by(humidity_cat) %>%
   summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2))

```

```{r}
#Proportion Distribution for Humidity VAribable for AQI Distribution

new_df %>% group_by(humidity_cat,AQI_Category) %>%
   summarise(Total_Count  = n()) %>% mutate(Perc_Contri= round(Total_Count/sum(Total_Count)*100,2)) %>%
  ggplot(aes(x = humidity_cat, y = Total_Count,fill= AQI_Category))+ 
  geom_bar(position = "fill",stat="identity",width =0.4, color = "Dark Green")+
       labs(x = "Humidity",
          y = "Proportion",
          title = "Data Distribution on Humidity")+
   scale_fill_brewer(palette = "Set1", direction = -1)

# No impact of humidity on Air Quality
```

```{r}
# Check effect of temperature on Air Quality

hist(new_df$tempC, 
     main = "Histogram for Temperature (째C)", 
     xlab = "Temperature (째C)",
     freq = TRUE,
     #probability = TRUE,
     breaks = 10,
     border = "Dark Blue",
     col = "light blue",
     labels = TRUE,
     las=1   ,
     ylim = c(0,1300))

# temperature scale is in the normal moderate range, hence would not influence AQI

```

```{r}
# Box Plot for Temperature
boxplot(new_df$tempC,
        las=1,
        main = "Box Plot for Temperature (째C)",
        #xlab = "Number of quantitues sold",
        ylab = "Temperature (째C)",
        col = "light blue",
        border = "dark blue",
        horizontal = F,
        outline = T)
```

```{r}
# Exporting the final dataset
setwd("D:/Semester 1/DANA/Team Project")
write.csv(new_df,"Final_Merged_Dataset.csv",row.names = FALSE)
```


